"""add cascade constraint to user role

Revision ID: 0715cf3e5445
Revises: 216d32b4d5f8
Create Date: 2023-03-28 19:31:40.200902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0715cf3e5445'
down_revision = '216d32b4d5f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
