"""add market status

Revision ID: 0a47280e0f2c
Revises: 87aada677a6f
Create Date: 2023-04-07 02:22:15.449951

"""
from alembic import op
import sqlalchemy as sa
import lib

# revision identifiers, used by Alembic.
revision = "0a47280e0f2c"
down_revision = "87aada677a6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "status",
        sa.Column("name", sa.String(length=24), nullable=True),
        sa.Column("id", lib.db.primary_key.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status")
    # ### end Alembic commands ###
