"""add password reset token to staff and customer model

Revision ID: 216d32b4d5f8
Revises: 7fe4159f2323
Create Date: 2023-03-28 16:31:36.343089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216d32b4d5f8'
down_revision = '7fe4159f2323'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('password_reset_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'password_reset_token')
    op.drop_column('customer', 'password_reset_token')
    # ### end Alembic commands ###
