"""add nullable to password_reset_token 

Revision ID: 35621bcfb5fb
Revises: ae31f991483b
Create Date: 2023-04-06 20:01:04.763336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35621bcfb5fb'
down_revision = 'ae31f991483b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'password_reset_token',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'password_reset_token',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
