"""init db

Revision ID: 85763a0f7c71
Revises: 744e45276c60
Create Date: 2023-03-24 18:14:10.137325

"""
from alembic import op
import sqlalchemy as sa
from src.lib.db import primary_key

# revision identifiers, used by Alembic.
revision = "85763a0f7c71"
down_revision = "744e45276c60"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_role_association",
        sa.Column("customer_id", primary_key.GUID(), nullable=False),
        sa.Column("permission_id", primary_key.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.PrimaryKeyConstraint("customer_id", "permission_id"),
    )
    op.drop_table("Customer_role_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Customer_role_association",
        sa.Column("customer_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("permission_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name="Customer_role_association_customer_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
            name="Customer_role_association_permission_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "customer_id", "permission_id", name="Customer_role_association_pkey"
        ),
    )
    op.drop_table("customer_role_association")
    # ### end Alembic commands ###
