"""created product: type, category, measuring_init, promo_code

Revision ID: b4d066511dfb
Revises: a0fc7033fed6
Create Date: 2023-04-03 22:53:17.979776

"""
from alembic import op
import sqlalchemy as sa
import src

# revision identifiers, used by Alembic.
revision = "b4d066511dfb"
down_revision = "a0fc7033fed6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_category",
        sa.Column("name", sa.String(length=24), nullable=True),
        sa.Column("id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_measuring_unit",
        sa.Column("unit", sa.String(length=24), nullable=True),
        sa.Column("id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_promo_code",
        sa.Column("code", sa.String(length=10), nullable=True),
        sa.Column("id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_type",
        sa.Column("name", sa.String(length=24), nullable=True),
        sa.Column("id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_type")
    op.drop_table("product_promo_code")
    op.drop_table("product_measuring_unit")
    op.drop_table("product_category")
    # ### end Alembic commands ###
