"""added product details

Revision ID: b7725395c0ce
Revises: b4d066511dfb
Create Date: 2023-04-04 17:34:08.381068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src

# revision identifiers, used by Alembic.
revision = "b7725395c0ce"
down_revision = "b4d066511dfb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("stock_unit", sa.Integer(), nullable=True),
        sa.Column("original_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("sale_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("discount", sa.Float(), nullable=True),
        sa.Column("sku", sa.String(length=16), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_series", sa.Boolean(), nullable=True),
        sa.Column("in_stock", sa.Boolean(), nullable=True),
        sa.Column("is_suspended", sa.Boolean(), nullable=True),
        sa.Column("id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_category_association",
        sa.Column("product_id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.Column("category_id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["product_category.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "category_id"),
    )
    op.create_table(
        "product_detail",
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("product_id", src.lib.db.primary_key.GUID(), nullable=True),
        sa.Column("id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_measuring_unit_association",
        sa.Column(
            "product_measuring_unit_id", src.lib.db.primary_key.GUID(), nullable=False
        ),
        sa.Column("product_id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_measuring_unit_id"],
            ["product_measuring_unit.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_measuring_unit_id", "product_id"),
    )
    op.create_table(
        "product_media",
        sa.Column("alt", sa.String(length=225), nullable=True),
        sa.Column("url", sa.String(length=225), nullable=True),
        sa.Column("content_type", sa.String(length=30), nullable=True),
        sa.Column("product_id", src.lib.db.primary_key.GUID(), nullable=True),
        sa.Column("id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_promo_code_association",
        sa.Column("product_media_id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.Column("product_id", src.lib.db.primary_key.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_media_id"], ["product_promo_code.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("product_media_id", "product_id"),
    )
    op.drop_table("product_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_type",
        sa.Column("name", sa.VARCHAR(length=24), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="product_type_pkey"),
    )
    op.drop_table("product_promo_code_association")
    op.drop_table("product_media")
    op.drop_table("product_measuring_unit_association")
    op.drop_table("product_detail")
    op.drop_table("product_category_association")
    op.drop_table("product")
    # ### end Alembic commands ###
