"""init db

Revision ID: f08b174d6edf
Revises: 85763a0f7c71
Create Date: 2023-03-24 18:15:54.820364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08b174d6edf'
down_revision = '85763a0f7c71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
