"""init db

Revision ID: f223cf4832f0
Revises: 
Create Date: 2023-03-26 20:42:40.689906

"""
from alembic import op
import sqlalchemy as sa
from src.lib.db.primary_key import GUID

# revision identifiers, used by Alembic.
revision = "f223cf4832f0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_token",
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(length=24), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_token")
    # ### end Alembic commands ###
